### ISSUE TITLE
Failing to install user.sh and GUI.sh + apt doesn't work

### ISSUE THREAD

**Issue by MohammedElansary-dev** [modded-ubuntu/modded-ubuntu#101]
When I use user.sh it finish with this error

```
./tracee/event.c:568: int handle_tracee_event(Tracee *, int): assertion "tracee->restart_how != PTRACE_CONT" failed
                           proot warning: signal 6 received from process 13376 
```

And after I run it again user.sh after restart I added a user name and password, then tried using gui.sh it wasn't there

I tried using `apt update` it doesn't work so I hade to use `dpkg configure -a` after using this command it  showed me this error 

```
Bad system call
./tracee/event.c:568: int handle_tracee_event(Tracee *, int): assertion "tracee->restart_how != PTRACE_CONT" failed
                           proot warning: signal 6 received from process 15360
``` 

------------------------------------------------------------
- Device: realme 5
- Android: 13 (custom rom)
- Ram: 3
- Free storage: 40
- Root: magisk (disabled for termux)
------------------------------------------------------------
Thank in advanced and  sorry for my bad English.

**Comment by BDhackers009** [comment]
Please give me the output of the command

` termux-info `
