### ISSUE TITLE
Updating existing installation

### ISSUE THREAD

**Issue by 0-Whoami** [modded-ubuntu/modded-ubuntu#102]
I have already installed previous version. Is there any way to install new version without loosing my data?

**Comment by BDhackers009** [comment]
> I have already installed previous version. Is there any way to install new version without loosing my data?

No its not possible till now . But you can take backup of your data by creating an archive of your files then reinstall modded-ubuntu then simply restore it. Also search for Backup/Restore in Linux terminal and you will get some ideas.
