### ISSUE TITLE
Can't get GUI properly 

### ISSUE THREAD

**Issue by SlimShadyAnonymous** [modded-ubuntu/modded-ubuntu#104]
![Screenshot_20230419_180743_VNC Viewer](https://user-images.githubusercontent.com/95496600/233077053-0dc88e01-0ef3-4b44-a304-60394524da2d.jpg)
Can't get GUI after running vncserver, just displaying square curser with some options on top left corner

**Comment by BDhackers009** [comment]
Run `vncstart` to start the vncserver and `vncstop` to stop the vncserver

**Comment by alpgithubx** [comment]
same problem here, vncstart or vncserver-start doesn't do anything

**Comment by BDhackers009** [comment]
> same problem here, vncstart or vncserver-start doesn't do anything

show the output when you use vncstart. If you dont give us proper info then we could not fix the issue because most of the users are getting the GUI properly.

**Comment by NPriyo** [comment]
> > same problem here, vncstart or vncserver-start doesn't do anything
> 
> show the output when you use vncstart. If you dont give us proper info then we could not fix the issue because most of the users are getting the GUI properly.

![Screenshot_2023-05-10-13-01-24-52_84d3000e3f4017145260f7618db1d683](https://github.com/modded-ubuntu/modded-ubuntu/assets/41458430/b675093c-b16f-4535-9044-f599ada61b69)
![Screenshot_2023-05-10-13-01-45-48_8659c1e795b4b4239e38d87c88c077b3](https://github.com/modded-ubuntu/modded-ubuntu/assets/41458430/508d37a0-c0c2-4e89-97de-be5396b7447b)

**Comment by BDhackers009** [comment]
well then good luck finding an alternative sir 🫡. Linux=errors/problems so you have to try to fix it not just uninstalling it.
