### ISSUE TITLE
gui not loading

### ISSUE THREAD

**Issue by alpgithubx** [modded-ubuntu/modded-ubuntu#107]
vncviewer shows a black screen with a square cursor.

**Comment by BDhackers009** [comment]
Please show the output of the terminal when you ran the `vncstart` command

**Comment by alpgithubx** [comment]
> Please show the output of the terminal when you ran the `vncstart` command

You chose dynamic resolution
Cleaning stale pidfile '/root/.vnc/localhost:5901.pid'!
Cleaning stale X11 lock '/tmp/.X1-lock'!
Cleaning stale X11 lock '/tmp/.X11-unix/X1'!

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd localhost:1 to connect to the VNC server.

VNC server started. The default password is the account password for root
root@localhost:~#

**Comment by BDhackers009** [comment]
run vncstart in user not as root
