### ISSUE TITLE
can't run ubuntu

### ISSUE THREAD

**Issue by ikhoeyZX** [modded-ubuntu/modded-ubuntu#108]
Followed guide but still stuck in here
![Screenshot_20230429_224911_Termux](https://user-images.githubusercontent.com/79812109/235308955-31319654-8ad4-44f0-ac31-615a270a4040.png)

**Comment by BDhackers009** [comment]
I see the user didnt created correctly. Please run

` proot-distro login ubuntu `
`bash user.sh` 

Then create a user then you can use `ubuntu` to log into Ubuntu

**Comment by ikhoeyZX** [comment]
Thanks the reason it won't make user because some package got collosion with yunu tool
I did remove.sh and setup.sh it works
Thanks
