### ISSUE TITLE
Touchpad/ Mouse not working 

### ISSUE THREAD

**Issue by SUMITDEY69** [modded-ubuntu/modded-ubuntu#110]
Hey Devs,
   I have accidentally turned off that option as shown in the image. And now I'm unable to use keyboard and mouse. How to enable that ??
Is there any way to enable it through terminal?

![IMG_20230508_000929](https://user-images.githubusercontent.com/108204481/236696389-4c12afee-b00d-4b8c-9c9f-7ddd178699d4.jpg)

               Hoping for a response.

**Comment by BDhackers009** [comment]
I don't have the exact solution but you can contact with me [BDhaCkers009](https://t. me/bdhackers009) via Telegram. Let's see if we can fix this

**Comment by SUMITDEY69** [comment]
Not working

**Comment by SUMITDEY69** [comment]
Thanks devs for solving this issue.
