### ISSUE TITLE
Session crashes, and when restarted vncstart hangs.

### ISSUE THREAD

**Issue by MarcusTL12** [modded-ubuntu/modded-ubuntu#111]
After installing, everything seemed to work fine, however after a few minutes the session crashed and when I try to restart termux (and even rebooting the phone) the ubuntu shell in termux works fine, but when running vncstart it just hangs there and the phone becomes quite hot. Any input on how to fix?

**Comment by BDhackers009** [comment]
This is because of "Phantom Proccess Killing". Here is the solution:- https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#how-to-disable-the-phantom-processes-killing
