### ISSUE TITLE
[HELP] How to download Software Center ?

### ISSUE THREAD

**Issue by SUMITDEY69** [modded-ubuntu/modded-ubuntu#114]
Hey Devs,,

Is there anyway to install Software Center.

     Hoping for your response 😄.

**Comment by BDhackers009** [comment]
To be honest I dont think so it will work because most of the software is downloaded from snap or flatpak in software center. But we cannot use snap in proot. Hope you will understand. But I will see if there any work around for this

**Comment by SUMITDEY69** [comment]
Okay
