### ISSUE TITLE
SU FAILURE

### ISSUE THREAD

**Issue by ydrk12** [modded-ubuntu/modded-ubuntu#119]
This seems to be the most commonly met fatal error on all the termux-based linuxs, and at a certain sense they have something in common like I used the debian sid or testing branch to update the packages (I just try to use apt-fast but have to fix R-4.1.3 and perl dependency problems! The stable branch cannot fit them so there is plenty of warnings of "broken packages" and stopped me from using apt!). However things become strange after a successful package upgrade:

```bash
[sudo] password for user1:
user1 is not in the sudoers file.
```

user1 was thrown out of sudoer list! Trying su the root

```bash
su: Authentication failure
```

But I got the right password! That's so absurd! Reusing the user.sh to creat a new sudoer user user2

```bash
user2 does not exist or not properly applied(I forget the original text, but this time, it will exit automatically because of a login failure)
```

And for another one modded debian i found on the internet, I met the same problem, so I guess this might be a bug for all of us (bad English, sorry for that). After using apt to upgrade some packages lead to this fatal error. 

I find the .bashrc_profile in the termux file system of the second modded debian and it showed me a file named userswitcher with:

exec su - user1

if is was "#" out, the modded system will not start and this warning is:

```bash
./start-androdeb.sh
su: Authentication failure
```

Please guys, for an unlucky fellow that is not able to own his own computer, the only one way that can save him is termux and modded Ubuntu, but this series is so broken and difficult. 

I AM NOT A LINUX EXPERT :(

**Comment by ydrk12** [comment]
This is the termux info:

```bash
termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13583
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
12
Kernel build information:
Linux localhost 4.19.191+ #1 SMP PREEMPT Wed Jun 14 19:19:22 CST 2023 aarch64 Android
Device manufacturer:
OPPO(yes, I am a whatever-you-call-it)
Device model:
PHJ110
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by BDhackers009** [comment]
Extremely sorry for the late. Seems like your user creation didn't work.You can reinstall it
