### ISSUE TITLE
can i start steam?

### ISSUE THREAD

**Issue by darastav** [modded-ubuntu/modded-ubuntu#122]
can i start steam?

**Comment by foodmaher** [comment]
No, I'm not work on develop this project but almost games on steam required 32bit or 64bit Intel/AMD to work properly as far as, the steam required translation layers from x86 or x64 to work on phones and translate windows instructions to be appropriate run on linux. So, if you want that, you can tried any emulator for wine x86/64x on android or going to advance progress steps as try to install windows ARM on your phone.

**Comment by foodmaher** [comment]
Sorry for my grammar 😁

**Comment by BDhackers009** [comment]
Thanks @foodmaher for showing the harsh reality. It is not possible to run any software that requires a 64bit or 32 bit cpu because the Ubuntu is running on your arm devices.
