### ISSUE TITLE
Vscode can't launch

### ISSUE THREAD

**Issue by vishwaravi** [modded-ubuntu/modded-ubuntu#125]
When l launch vscode editor it shows some error like this 👇
![Screenshot_2023-09-25-12-39-28-619_com realvnc viewer android](https://github.com/modded-ubuntu/modded-ubuntu/assets/128621045/c0b3fc7d-59de-4d7b-99f3-5f63f856f097)
Pls kindly Help me to solve this issue.

**Comment by BDhackers009** [comment]
seems like vs code didnt installed correctly.
