### ISSUE TITLE
Vnc not starting

### ISSUE THREAD

**Issue by ARAtik169** [modded-ubuntu/modded-ubuntu#128]
Vnc process Empty
![Screenshot_20231011_052312_Termux](https://github.com/modded-ubuntu/modded-ubuntu/assets/73770372/26315fdd-ba3f-4b14-a93d-034864f58a41)

**Comment by Vyshkkg** [comment]
Same issue 🙂🖐

**Comment by BDhackers009** [comment]
did you do any modification to the script ?

**Comment by ARAtik169** [comment]
No

**Comment by BDhackers009** [comment]
Okay message me on [telegram](t.me/bdhackers009). Lets see if we can fix it.

**Comment by parthasdey2304** [comment]
would you please assign this to me..

**Comment by ARAtik169** [comment]
Uninstall the modded ubuntu & reinstall it🙂 that's will do the trick

**Comment by BDhackers009** [comment]
> Uninstall the modded ubuntu & reinstall it🙂 that's will do the trick

Yeah. Because sometime when installing the prooted environment some packages do not get installed properly thats why those type of problem occurs.
