### ISSUE TITLE
Vnc not work...

### ISSUE THREAD

**Issue by VaMPIRESqq** [modded-ubuntu/modded-ubuntu#131]
![Screenshot_2023-11-07-09-45-09-107_com.realvnc.viewer.android.jpg](https://github.com/modded-ubuntu/modded-ubuntu/assets/146086035/05d7ea3e-e304-41f9-bb3e-c983f28972a5)

![Screenshot_2023-11-07-09-45-19-760_com.realvnc.viewer.android.jpg](https://github.com/modded-ubuntu/modded-ubuntu/assets/146086035/f15cd9f3-36d4-4482-9846-597b38b37f3d)

**Comment by BDhackers009** [comment]
Did the installation of gui.sh was completed? If yes then please show me the output of `vncstart`

**Comment by Capitasas** [comment]
I'm having the same problem and the output is "New Xtigervnc server 'modded-ubuntu' on port (idk if this can be shared) for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.73GftN/passwd :1 to connect to the VNC server."
