### ISSUE TITLE
How connect from pc?

### ISSUE THREAD

**Issue by Vediforce** [modded-ubuntu/modded-ubuntu#132]
![image](https://github.com/modded-ubuntu/modded-ubuntu/assets/86305600/10372f75-3091-4e39-84b0-0d0e3ae82bf5)

**Comment by RebornOfc** [comment]
I opened `nano $(which vncstart)`, then after implementing **-localhost no** between **dbus-launch** and **-geometry** I could open it at my pc.

`dbus-launch -localhost no -geometry 1280x720 ...`

**Comment by freebrowser1** [comment]
You can retain localhost:yes and run an ssh tunnel, which is more secure. Plain VNC is unencrypted but SSH is.
Run from terminal (in Windows Powershell has ssh) `ssh -L 6901:localhost:5901 user@deviceip`
Then in the VNC viewer on the PC connect to localhost:6901.
