### ISSUE TITLE
The connection closed unexpectedly

### ISSUE THREAD

**Issue by agcrisbp** [modded-ubuntu/modded-ubuntu#138]
![Screenshot_2024-01-11-04-55-41-763_com termux-edit](https://github.com/modded-ubuntu/modded-ubuntu/assets/54905291/5f60431b-cca4-42dd-9120-48f171da0598)
![Screenshot_2024-01-11-04-55-23-665_com realvnc viewer android-edit](https://github.com/modded-ubuntu/modded-ubuntu/assets/54905291/4765ddd3-30df-438e-9aa2-1b4400b16bc6)

**Comment by agcrisbp** [comment]
nvm, i found a way to fix it

**Comment by Waltuh-dawhite** [comment]
How did you fix it?
