### ISSUE TITLE
VNC viewer loading forever

### ISSUE THREAD

**Issue by Leo-MathGuy** [modded-ubuntu/modded-ubuntu#14]
After doing vncstart, I opened up vnc viewer, but is says "Connecting..." forever. It doesn't do "The connection could not be established" or any error, but just waiting.

**Comment by ShivaShirsath** [comment]
[install vnc](https://github.com/ShivaShirsath/VNC) use this to install vnc 
And it's very interactive, also touch use.

**Comment by JAKYT124** [comment]
I also have the same problem.

**Comment by ShivaShirsath** [comment]
> [install vnc](https://github.com/ShivaShirsath/VNC) use this to install vnc And it's very interactive, also touch use.

Try this
