### ISSUE TITLE
Vncserver kills itself on startup

### ISSUE THREAD

**Issue by BurningSpy** [modded-ubuntu/modded-ubuntu#140]
Hi, on startup of vncserver I get following error:

Cleaning stale pidfile '/home/ls/.vnc/localhost.localdomain:1.pid'!

New Xtigervnc server 'localhost.localdomain:1 (ls)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.XlBzHE/passwd :1 to connect to the VNC server.

=================== tail /home/ls/.vnc/localhost.localdomain:1.log ===================
[mi] mieq: warning: overriding existing handler (nil) with 0x300015e2e0 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x300015e2e0 for event 3
X connection to :1 broken (explicit kill or server shutdown).

Sat Feb  3 12:06:50 2024
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)
Killing Xtigervnc process ID 21031... success!
======================================================================================

Session startup via '/etc/X11/Xtigervnc-session' cleanly exited too early (< 3 seconds)!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session cleanly exited!
The Xtigervnc server cleanly exited!

---------

Any idea how I can fix this?

**Comment by BDhackers009** [comment]
Try
``` vncserver -xstartup /usr/bin/xfce4-session```

**Comment by BurningSpy** [comment]
Hi, my bad.
I just realised that I had to use vncstart instead of vncserver as command. 
With vncstart it worked fine.
