### ISSUE TITLE
Unable to install Libreoffice 

### ISSUE THREAD

**Issue by SUMITDEY69** [modded-ubuntu/modded-ubuntu#145]
Hey devs,
      I was planning to install "Libreoffice", but when I tried it isn't installing.
      I have attached the screenshot, check that out.
![Screenshot_2024-03-23-22-26-05-81_84d3000e3f4017145260f7618db1d683](https://github.com/modded-ubuntu/modded-ubuntu/assets/108204481/f6be16ab-e3a4-4ea5-94aa-f12606d21bc4)

       Hoping for your response

**Comment by BDhackers009** [comment]
Did you added any other distros repo in sources.list?

**Comment by SUMITDEY69** [comment]
Wait let me check

**Comment by SUMITDEY69** [comment]
![Uploading Screenshot_2024-03-23-22-39-39-37_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by SUMITDEY69** [comment]
![Screenshot_2024-03-23-22-39-39-37_84d3000e3f4017145260f7618db1d683](https://github.com/modded-ubuntu/modded-ubuntu/assets/108204481/e030fa7a-76a6-420e-a2e9-df0d861556f3)

**Comment by SUMITDEY69** [comment]
Check this out

**Comment by BDhackers009** [comment]
show output of

``` cat /etc/apt/sources.list.d/*.list ```

**Comment by SUMITDEY69** [comment]
![Screenshot_2024-03-23-22-56-26-41_84d3000e3f4017145260f7618db1d683](https://github.com/modded-ubuntu/modded-ubuntu/assets/108204481/66b50428-993a-4780-b7dd-5f132a0b582c)

**Comment by BDhackers009** [comment]
@bdhackers009 dm me in telegram. Let me try to fix this.

**Comment by SUMITDEY69** [comment]
give your telegram I'd name
