### ISSUE TITLE
unminimize fail

### ISSUE THREAD

**Issue by matyle** [modded-ubuntu/modded-ubuntu#15]
Updating certificates in /etc/ssl/certs...       0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...done.
Errors were encountered while processing:         udisks2
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by BDhackers009** [comment]
just remove the file called udisks2.postinst in the direcotry /var/lib/dpkg/info

the proper command is:- 

sudo rm /var/lib/dpkg/info/udisks2.post* && sudo dpkg --configure -a && sudo apt  update && sudo apt upgrade -y
