### ISSUE TITLE
cannot setup ubuntu, or log in

### ISSUE THREAD

**Issue by enisfleur** [modded-ubuntu/modded-ubuntu#150]
so i followed every single step of the guide and even watched the video and i get these errors.
![Screenshot_20240515-213629_Termux](https://github.com/modded-ubuntu/modded-ubuntu/assets/78642947/ceebd759-22a8-4faa-9a90-ecc6cbbf2794)
even when i open "bash setup.sh" i get "distro and packages already installed"
![image](https://github.com/modded-ubuntu/modded-ubuntu/assets/78642947/20c398d0-217b-45c6-9034-9a811e7aed53)

**Comment by BDhackers009** [comment]
can you show the output of

$ proot-distro list

I just wanted to check if the ubuntu distro is installed or not

**Comment by plants8332** [comment]
> can you show the output of
> 
> $ proot-distro list
> 
> I just wanted to check if the ubuntu distro is installed or not

![Screenshot_20240522-005328_Termux.png](https://github.com/modded-ubuntu/modded-ubuntu/assets/78642947/43208d33-1941-406b-99c4-8b2806ea7eac)

yes, the distro is installed. but there is 2 ubuntu lts appearing and theyre not installed (i think it doesnt matter).

**Comment by BDhackers009** [comment]
Try to login using 

$ ` proot-distro login ubuntu`

if it logins to Ubuntu then run the remove script from the modded-ubuntu folder and re run the setup.
