### ISSUE TITLE
man not working after unminimize

### ISSUE THREAD

**Issue by alwzfolwd** [modded-ubuntu/modded-ubuntu#2]
I've unminimized the system three times now and still everytime I try to use man I get,

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.              
To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.

I've checked and man-db is installed and updated. I've updated and searched for a problem with no results.

**Comment by BDhackers009** [comment]
I encountered same things in ubuntu docker image, to get whole package which ubuntu or concern os offers normally, just execute unminimize

collected from kcubterm sir🙊

**Comment by BDhackers009** [comment]
@alwzfolwd I encountered same things in ubuntu docker image, to get whole package which ubuntu or concern os offers normally, just execute unminimize..it will take spece....

collected from kcubterm sir!
