### ISSUE TITLE
Error: missing plugin for distribution 'ubuntu-20.04'.

### ISSUE THREAD

**Issue by ShivaShirsath** [modded-ubuntu/modded-ubuntu#21]
By updating proot-distro this error gets occurred
How to get backup of this distro

**Comment by DepressoMocha** [comment]
Well, i found a way to install it because apparently you can't downgrade proot distro.

In modded-ubuntu, use command `nano setup.sh` and replace `ubuntu-20.04` with `ubuntu`. It should work perfectly

**Comment by ShivaShirsath** [comment]
The all installation & projects going to vanish 

I cleaned my termux & installed ubuntu from proot-distro

**Comment by DepressoMocha** [comment]
> The all installation & projects going to vanish
Really? Well, i guess i didn't notice it because i am starting with clean slate haha. And, you're welcome!

**Comment by ShivaShirsath** [comment]
😊
