### ISSUE TITLE
Getting Error While Running bash setup.sh

### ISSUE THREAD

**Issue by ghost** [modded-ubuntu/modded-ubuntu#22]
Hello,
When i try to run bash setup.sh it throws me this error.

```
> Checking required packages...
> 
> Directory '~/storage' is going to be wiped. No storage contents will be touched.
> 
> Do you want to continue ? (y/n) y
> 
>  [-] Packages already installed.
> 
>  [-] Checking for Distro...
> 
> Error: unknown distribution 'ubuntu-20.04' was requested to be installed.
> 
> Run 'proot-distro list' to see the supported distributions.
> 
>  [-] Error Installing Distro !
> 
```

**Comment by DepressoMocha** [comment]
Try using command `nano setup.sh` and replace `ubuntu-20.04` with `ubuntu` before running it with bash. Do the same for `user.sh`

**Comment by Nasyx-Rakeeb** [comment]
When i give command nano setup.sh i see ubuntu-20.04 atleast 7-8 times which one should i replace

**Comment by DepressoMocha** [comment]
All of them

**Comment by DepressoMocha** [comment]
That's odd, the method works perfectly for me. Also, i checked, and apparently they updated the setup.sh and user. sh, maybe you should check it and see if it works?

**Comment by Nasyx-Rakeeb** [comment]
> That's odd, the method works perfectly for me. Also, i checked, and apparently they updated the setup.sh and user. sh, maybe you should check it and see if it works?

I tried everything but sll in vain. 
Does it require root???

**Comment by DepressoMocha** [comment]
I don't think so. My phone isn't rooted and i can still use it normally.
