### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by AndVer0** [modded-ubuntu/modded-ubuntu#24]
first thank you for this modded ubuntu it very helpful I have more idea example:
add pycharm (ide for ubuntu) is a python ide. pycharm support 32 bit and 64 bit and his a better choice for any python develloper he support vm or ubuntu + vnc for termux but problem is big (1.4Gb)

**Comment by ShivaShirsath** [comment]
Just install android studio  ( openjdk 15 required for installing [jdk installation](https://github.com/ShivaShirsath/Install-JDK-in-Ubuntu)  ) 
It can run java, kotlin, python, markdown, bash, dart, android, flutter, etc etc all 

Try Python in android studio ( just drag your python file or folder on android studio icon )
