### ISSUE TITLE
Xfce icons won't display

### ISSUE THREAD

**Issue by w3r3wolv3s** [modded-ubuntu/modded-ubuntu#27]
Problem:
When launching the Xfce desktop, no icons will display, or a "placeholder" icon will show instead.

Expected:
Icons will display properly, rather than an empty area or placeholder icon.

Proposed Solution:
It seems that **librsvg2-common** is missing from the installation. `sudo apt install librsvg2-common` solves the issue, and icons display properly.

**Comment by BDhackers009** [comment]
> Problem: When launching the Xfce desktop, no icons will display, or a "placeholder" icon will show instead.
> 
> Expected: Icons will display properly, rather than an empty area or placeholder icon.
> 
> Proposed Solution: It seems that **librsvg2-common** is missing from the installation. `sudo apt install librsvg2-common` solves the issue, and icons display properly.

Very very thanks for providing the solution we have added the package in to our script
