### ISSUE TITLE
vncstart

### ISSUE THREAD

**Issue by debjyotikumarrana1** [modded-ubuntu/modded-ubuntu#28]
deb@localhost:~$ vncstart

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/deb/.vnc/passwd localhost.localdomain:1 to connect to the VNC server.

=================== tail /home/deb/.vnc/localhost.localdomain:5901.log ===================
==========================================================================================

Session startup via '/home/deb/.vnc/xstartup' cleanly exited too early (< 3 seconds)!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session cleanly exited!
Killing Xtigervnc process ID 18737... success!
deb@localhost:~$

![IMG_20210912_205104](https://user-images.githubusercontent.com/86921756/132993271-a90900b0-1c58-4fd0-a8a4-32cdee65df40.jpg)

**Comment by w3r3wolv3s** [comment]
What's the output of your log file. I would bet this is the same issue as I had:
https://github.com/modded-ubuntu/modded-ubuntu/issues/26

**Comment by Aquib001** [comment]
I am also facing this same issue

**Comment by w3r3wolv3s** [comment]
> I am also facing this same issue

You might want to try the solution I proposed in issue #26 and let us know if it works for you.

**Comment by Uxtrom** [comment]
I am also facing this issue because of this 
![Uploading Screenshot_20211007-115818.png…]()

**Comment by TiraCoder** [comment]
> deb@localhost:~$ vncstart
> 
> New Xtigervnc server 'remote-desktop' on port 5901 for display :1. Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/deb/.vnc/passwd localhost.localdomain:1 to connect to the VNC server.
> 
> # =================== tail /home/deb/.vnc/localhost.localdomain:5901.log ===================
> Session startup via '/home/deb/.vnc/xstartup' cleanly exited too early (< 3 seconds)!
> 
> Maybe try something simple first, e.g., tigervncserver -xstartup /usr/bin/xterm The X session cleanly exited! Killing Xtigervnc process ID 18737... success! deb@localhost:~$
> 
> ![IMG_20210912_205104](https://user-images.githubusercontent.com/86921756/132993271-a90900b0-1c58-4fd0-a8a4-32cdee65df40.jpg)

 cd /root/.vnc
sudo rm * 
vncserver
Config new passwor 
That fixed 😉

**Comment by TiraCoder** [comment]
![Uploading Screenshot_20220212-192603_NetHunter Terminal.jpg…]()
