### ISSUE TITLE
proot-distro is not avaliable for me :(

### ISSUE THREAD

**Issue by BadPing444** [modded-ubuntu/modded-ubuntu#34]

**Comment by Mecha-Labs** [comment]
> _No description provided._

try changing the repository to x11-repo

**Comment by BadPing444** [comment]
> > _No description provided._
> 
> try changing the repository to x11-repo

is not posible cause my android is 6.0.1 and i don't have x11 repository

**Comment by BDhackers009** [comment]
try installing it manually

apt update && apt upgrade  -y && apt install git -y && git clone https://github.com/termux/proot-distro && cd proot-distro && bash install.sh

then install the modded Ubuntu 🤔
