### ISSUE TITLE
Vnc viewer problem

### ISSUE THREAD

**Issue by 2589kali** [modded-ubuntu/modded-ubuntu#35]
mokn08@localhost : vncstart

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/moon08/.vnc/passwd localhost.localdomain:1 to connect to the VNC server.

=================== tail /home/moon08/.vnc/localhost.localdomain:5901.log ===================
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-i4z1AADRBC,guid=3a68f83751737010eee02a796156a7e1
DBUS_SESSION_BUS_PID=18334
DBUS_SESSION_BUS_WINDOWID=2097153
=============================================================================================

Session startup via '/home/moon08/.vnc/xstartup' cleanly exited too early (< 3 seconds)!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session cleanly exited!
Killing Xtigervnc process ID 18297... success!

After opening vnc viewwe : this port.........
Fix the problem

**Comment by BDhackers009** [comment]
sir please show us the output of

cat $(which vncstart)

**Comment by ilyasahmadalmaki** [comment]
Try!
apt install xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils

**Comment by storytellerF** [comment]
> sir please show us the output of
> 
> cat $(which vncstart)

```shell
#!/usr/bin/env bash
dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name modded-ubuntu -xstartup /usr/bin/xfce4-session
```
