### ISSUE TITLE
root@termux[~]: # ubuntu root@localhost:~# bash gui.sh bash: gui.sh: No such file or directory

### ISSUE THREAD

**Issue by iExly** [modded-ubuntu/modded-ubuntu#38]
After exucuting bash user.sh
 And install correctly but when i restart my termux and i type ubuntu and type bash gui.sh 
Its says :- root@termux[~]:
# ubuntu
root@localhost:~# bash gui.sh
bash: gui.sh: No such file or directory

Please help me about this i don't know what happened 

![Screenshot_2021-10-14-12-46-20-30_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/87321079/137269641-af7e6355-94e5-4c62-9feb-20ca238f4769.jpg)
 See the image

**Comment by Bobombn64** [comment]
I have the same problem too, i tried so many different thing, still no success. 
I am currently at my 5th attempt

**Comment by Bobombn64** [comment]
Ok, thank you^^

**Comment by Bobombn64** [comment]
@BDhackers009 your English is fine don't worry^^

And everything worked but there is this problem with starting a vnc server.
![Screenshot_2021-10-16-23-50-14-515_com termux](https://user-images.githubusercontent.com/83509013/137602947-fe4768c1-e5a4-49ad-af6b-09b775b432d7.jpg)

**Comment by Bobombn64** [comment]
Well i got it to work with #26 but now there's that problem 
![Screenshot_2021-10-17-00-19-55-129_com iiordanov freebVNC](https://user-images.githubusercontent.com/83509013/137603485-1ffe2f40-1cd8-4ffb-aa93-5f720e6cc43d.jpg)

**Comment by BDhackers009** [comment]
@Bobombn64  after running "sudo apt install librsvg2-common" restart ur termux and change icons from applications>settings>appearance

**Comment by BDhackers009** [comment]
@Bobombn64 possible sir...... inshallah we will make a script of lxde DE but you have to wait for a few month... because our exam is running 🥺

**Comment by Danhack15** [comment]
Me too the same problem

**Comment by Banane79** [comment]
Omg cant someone install it on my Phone ? My brain is overheating !"!!""!!"

**Comment by sachinyadavsre** [comment]
~/root $ sudo airmon-ng                                 No superuser binary detected.
Are you rooted?
~/root $

**Comment by sachinyadavsre** [comment]
How can fix it

**Comment by Ammarrahimi2030** [comment]
@BDhackers009

**Comment by BDhackers009** [comment]
> ~/root $ sudo airmon-ng No superuser binary detected. Are you rooted? ~/root $

Modded-ubuntu is based on proot(fake root) which means you cannot run any tool that requires actual permission for hardware technologies like WiFi, Bluetooth
