### ISSUE TITLE
Vncserver not starting

### ISSUE THREAD

**Issue by Meharaj007** [modded-ubuntu/modded-ubuntu#40]

**Comment by Meharaj007** [comment]
$ vncstart                           DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-go4ptt5iXX,guid=88e71b2eb0caa0c7928b92ad6184fbf4               DBUS_SESSION_BUS_PID=21152
/usr/local/bin/vncstart: line 3: vncserver: command not found

**Comment by Meharaj007** [comment]
@BDhackers009

**Comment by Meharaj007** [comment]
![Screenshot_20211105-151013796](https://user-images.githubusercontent.com/93766839/140491875-d5cab833-e5d1-45df-a273-711eef157efd.jpg)

**Comment by BDhackers009** [comment]
show output of

cat $(which vncstart)

**Comment by Meharaj007** [comment]
![Screenshot_20211105-151013796](https://user-images.githubusercontent.com/93766839/140624492-2e1913b2-d532-49f4-835a-90909ad02e0b.jpg)

**Comment by Meharaj007** [comment]
![Screenshot_20211105-173049377](https://user-images.githubusercontent.com/93766839/140624511-1ea848c8-b306-4000-80f6-fe766493aadb.jpg)

**Comment by Meharaj007** [comment]
@BDhackers009

**Comment by BDhackers009** [comment]
seems like u dont have tigervnc installed...


try

sudo apt install xfce4 xfce4-session xfce4-terminal tigervnc* -y 

then run vncstart

**Comment by Temuxuser2021** [comment]
Ar you guys fool ot what its not vncstart. Its vncserver-start or vncserver-stop

**Comment by BDhackers009** [comment]
> Ar you guys fool ot what its not vncstart. Its vncserver-start or vncserver-stop

vncserver-start && vncserver-stop aren't any command they are just alias for running vncserver. The developers of andronix && anlinux created vncserver-start && vncserver-stop so that the users can use run && stop vncserver easily. In the same way we made vncstart && vncstop so that the users can easily run && stop vncserver. Got it sir?
