### ISSUE TITLE
No icon is showing on desktop please help me!

### ISSUE THREAD

**Issue by madhu9418** [modded-ubuntu/modded-ubuntu#44]
I've successfully installed that modded-ubuntu os on my android via termux. Into the installation process i got an error something like -
../tmp/apt-key-gpghome.11RokJkLFW/gpg.1.sh -qq --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys ED444FF07D8D0BF6.....
...this may a server issue....( i can't remember it properly) 
By the way after the installation when I start the vncserver and connect with it I got the desktop without any icon showing and it's hard to recognize everything there . here is a scren shot of that issue 
![Screenshot_2021-12-17-18-35-00-425_com realvnc viewer android](https://user-images.githubusercontent.com/82604107/146548948-221d70ef-8e97-4875-92ac-a14ae1abe06d.jpg)
Please help me to solve my issue!!
@BDhackers009  please help me!

**Comment by BDhackers009** [comment]
../tmp/apt-key-gpghome.11RokJkLFW/gpg.1.sh -qq --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys ED444FF07D8D0BF6..... 

Ignore that....its not an issue...and to fix icon you have to install a package .....and change your icon from applications>settings>appearance.

to install that package type below command in your ubuntu machine:

sudo apt install librsvg2-common

and then restart your ubuntu 

Restating ubuntu means stop vncserver then close termux then again open termux and login to ubuntu and then start vncserver 🙆.

Hope it will help.

**Comment by madhu9418** [comment]
@BDhackers009  hopefully it works , thanks man!
