### ISSUE TITLE
Every time VNC display number get changed!

### ISSUE THREAD

**Issue by madhu9418** [modded-ubuntu/modded-ubuntu#45]
Everytime i type `ubuntu`  and then `vncstart` the display number is getting changed and something warning like is showing here is the output -

```
vncstart
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-AMjLzE6ua4,guid=937b89edddfc212074fe578161bc8bad
DBUS_SESSION_BUS_PID=20041

Warning: localhost.localdomain:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server localhost.localdomain:1

Warning: localhost.localdomain:1 is taken because of /tmp/.X1-lock
Remove this file if there is no X server localhost.localdomain:1

Warning: localhost.localdomain:2 is taken because of /tmp/.X11-unix/X2
Remove this file if there is no X server localhost.localdomain:2

Warning: localhost.localdomain:2 is taken because of /tmp/.X2-lock
Remove this file if there is no X server localhost.localdomain:2

New Xtigervnc server 'localhost.localdomain:3 (malay)' on port 5903 for display :3.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/malay/.vnc/passwd :3 to connect to the VNC server.
```

And that's why i have to change that display number on vnc viewer application everytime i wanna connect to it . how to solve this please help!
Here is a screen shot what i'm getting 
![Screenshot_2021-12-17-18-42-08-406_com termux](https://user-images.githubusercontent.com/82604107/146549731-b688f7f9-7d90-437b-a9e1-8f0a6224c3b0.jpg)
@BDhackers009  please help me!

**Comment by BDhackers009** [comment]
this is because u didn't use vncstop command before u close termux....

To fix it type ubuntu to login on ubuntu and then sudo rm -rf ~/.vnc

then setup your vncserver again by typing vncstart....and then use vncstop
everything time u close termux.

Hope it will help you sir.Ingore my bad English

**Comment by madhu9418** [comment]
@BDhackers009  Yes the problems is solved thank you man !!

**Comment by madhu9418** [comment]
@BDhackers009  please bro i have a another problem I posted the issue here
 https://github.com/modded-ubuntu/modded-ubuntu/issues/44#issue-1083241884
Can you please help me to figure out what is the problem here?
