### ISSUE TITLE
Nothing can be executed from desktop

### ISSUE THREAD

**Issue by madhu9418** [modded-ubuntu/modded-ubuntu#46]
Yeah! It's not a issue but still I want a solution for it
Whenever i'm trying to execute from desktop it showing me a pop 
![Screenshot_2021-12-19-18-05-35-946_com realvnc viewer android](https://user-images.githubusercontent.com/82604107/146675661-d6227234-c6bd-4a4b-8713-ea26c38267e8.jpg)
Can you please tell me what to do?
NOTE: I know I can do it manually by giving it the execute permission of it's properties section. But I want it to stop showing permanently, I can't manually give permission to all of the things on my desktop. Please help me @BDhackers009  🤧

**Comment by BDhackers009** [comment]
just click "mark executable" when the pop up comes...then it will never
come for that application
