### ISSUE TITLE
bash user.sh error

### ISSUE THREAD

**Issue by shamil-lol** [modded-ubuntu/modded-ubuntu#49]
root@localhost:~# bash user.sh
bash: user.sh: No such file or directory

**Comment by BDhackers009** [comment]
please show the output of 
$ ls ~

**Comment by shamil-lol** [comment]
no output 
root@localhost:~$ ls
root@localhost:~$ ls
root@localhost:~$ ls

**Comment by BDhackers009** [comment]
> no output root@localhost:~$ ls root@localhost:~$ ls root@localhost:~$ ls

kindly reinstall modded-ubuntu sir
you can do it by executing:- 
$ ` cd ~/modded-ubuntu && bash remove.sh && sleep 2 &&  bash setup.sh `

**Comment by HackerBrine2004** [comment]
> > no output root@localhost:~$ ls root@localhost:~$ ls root@localhost:~$ ls
> 
> kindly reinstall modded-ubuntu sir you can do it by executing:- $ `cd ~/modded-ubuntu && bash remove.sh && sleep 2 && bash setup.sh`



> 

Sir when jammy jellyfish will come in  the modded ubuntu

**Comment by BDhackers009** [comment]
As soon as the Termux devs push the updates😌

**Comment by HackerBrine2004** [comment]
I'm am very grateful to the modded ubuntu devs for making it I'm liking it a lot and thanks for the instant support i wish you a very good luck for future🙏
Sir also wanted to add that plz make it compatible to run edex ui.☺️

**Comment by BDhackers009** [comment]
> I'm am very grateful to the modded ubuntu devs for making it I'm liking it a lot and thanks for the instant support i wish you a very good luck for future🙏 Sir also wanted to add that plz make it compatible to run edex ui.☺️

it's already compatible to run edex-ui download edex appimage according to your cpu architecture then mark it as "run as program" from the appimage properties then simply run that...but I want to warn if you have a nice number of ram than don't run edex-ui because it can hang your device

**Comment by HackerBrine2004** [comment]
Sir after installing the arm64 appimage i am running it as program it is showing 

Cannot mount appimage, please check your fuse setup
You might still be able to extract the contents of this Appimage if you run it with the-appimage-extract option See https://github.com/Appirnage/Appimagewiki/Fuse

**Comment by BDhackers009** [comment]
> Sir after installing the arm64 appimage i am running it as program it is showing
> 
> Cannot mount appimage, please check your fuse setup You might still be able to extract the contents of this Appimage if you run it with the-appimage-extract option See https://github.com/Appirnage/Appimagewiki/Fuse

Try to run the appimage in terminal using ./ then send ss of output

**Comment by HackerBrine2004** [comment]
![Uploading Screenshot_2022-05-04-10-08-56-015_com.offsec.nethunter.kex.jpg…]()
 Sir this is the ss.

**Comment by BDhackers009** [comment]
your ss didnt come well please send ss perfectly

**Comment by HackerBrine2004** [comment]
> 

Sir i have also sent ss via gmail

**Comment by BDhackers009** [comment]
wel I dont get the ss

**Comment by HackerBrine2004** [comment]
Sir plz provide a particular gmail where i may send the ss

**Comment by BDhackers009** [comment]
> Sir plz provide a particular gmail where i may send the ss

send the ss in my telegram :- @bdhackers009

**Comment by HackerBrine2004** [comment]
Yes sir sent thank you

**Comment by BDhackers009** [comment]
You're welcome!

**Comment by HackerBrine2004** [comment]
Sir this is the ss
