### ISSUE TITLE
IMAGE OR ANY OTHER FILE IS NOT OPENING

### ISSUE THREAD

**Issue by 0-Whoami** [modded-ubuntu/modded-ubuntu#52]
Sir I tried to set the wallpaper of xfce but when I opened the desktop folder on imege is showing.I tried many times and many other methods like -
Feh
But nothing happened  .
Please help

**Comment by BDhackers009** [comment]
Please! Make a small screen record of your problem and send me 😕 because I cant able to understand your problem 😔

**Comment by HackerBrine2004** [comment]
Plz can you make modded manjaro, a very very big fan of modded ubuntu, thank you so much for making it

**Comment by BDhackers009** [comment]
> Plz can you make modded manjaro, a very very big fan of modded ubuntu, thank you so much for making it

Now we are trying to make our modded-ubuntu far better after that we will focus on new distributions. Thnaks

**Comment by 0-Whoami** [comment]
> 

Sir icons are not showing

**Comment by BDhackers009** [comment]
> > 
> 
> Sir icons are not showing

Are you using the latest version? I mean we already fix the icon releted problem. Can you provie us some screenshot of your problem?

**Comment by HackerBrine2004** [comment]
Thank you so much sir for giving reply its an honour to use modded ubuntu
and I'm likely requesting you to make further ubuntu upgrade to 22.04 jammy
jellyfish. Thank you once again.
