### ISSUE TITLE
VS code is not running

### ISSUE THREAD

**Issue by malay9418** [modded-ubuntu/modded-ubuntu#58]
idk why double tapping on the vs code icon, nothing's happening. 
the output of
`$code --verbose`

`setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/code/chrome-sandbox is owned by root and has mode 4755`

![Screenshot_2022-03-27-09-31-13-100_com realvnc viewer android](https://user-images.githubusercontent.com/97306538/160266597-90672024-c500-43dc-a876-5740ef231bec.jpg)
![Screenshot_2022-03-27-09-31-17-967_com realvnc viewer android](https://user-images.githubusercontent.com/97306538/160266605-bcee61e0-bea1-4fa4-aa8b-45f70f97c2c6.jpg)

@htr-tech @BDhackers009  help please : (

**Comment by BDhackers009** [comment]
use

code --no-sanbox

for running vscode.....

**Comment by malay9418** [comment]
@BDhackers009 yah, your solution worked, but can you please explain me what is `sandbox` and why is this type of error occuring?:

**Comment by BDhackers009** [comment]
> 

Honestly I dont know actually what that thing is but I know how to fix it. btw sanbox is an isolated environment with which you can run a piece of code or a software without affecting your system.

**Comment by HackerBrine2004** [comment]
https://youtu.be/Fd59maVTG58 
See this video from start

**Comment by BDhackers009** [comment]
> https://youtu.be/Fd59maVTG58 See this video from start

💁 Thanks for showing us the easier fix we will patch this in the next update
