### ISSUE TITLE
access and modify files and directories from my phone

### ISSUE THREAD

**Issue by iamist** [modded-ubuntu/modded-ubuntu#6]
I would like to access file and directory from android and use app installed on my phone to write codes NOT through VNC interface. Is this possible? thanks

**Comment by BDhackers009** [comment]
> I would like to access file and directory from android and use app installed on my phone to write codes NOT through VNC interface. Is this possible? thanks

**Comment by htr-tech** [comment]
using terminal go to this directory `/storage/emulated/0` 

here you will find your internal storage

**Comment by iamist** [comment]
@htr-tech , thanks'! i can view and creat file to that directory but I'm getting permissions warning and if I tried npm install, there's a permission issue on symlinks

**Comment by htr-tech** [comment]
> @htr-tech , thanks'! i can view and creat file to that directory but I'm getting permissions warning and if I tried npm install, there's a permission issue on symlinks

copy the files to ubuntu home & try 🤔
