### ISSUE TITLE
tigervncpasswd??

### ISSUE THREAD

**Issue by min6436k** [modded-ubuntu/modded-ubuntu#63]
![Screenshot_20220504-231213_Termux](https://user-images.githubusercontent.com/46528927/166699862-703dc67f-cfd5-4027-b9a1-e4cc8c05ac20.jpg)

Help me..

**Comment by BDhackers009** [comment]
Well this problem is for the ubuntu version jammy. you can fix this by installing package :- sudo apt install tigervnc-tools
