### ISSUE TITLE
I can't connect to vnc 

### ISSUE THREAD

**Issue by Aguma-adi** [modded-ubuntu/modded-ubuntu#68]
Wherever i type vncstart it shows nothing and i cant connect to vnc🥲

**Comment by muznabin12** [comment]
I'm also having the same problem.
![Screenshot_20220620-025325_Termux](https://user-images.githubusercontent.com/52606690/174500038-59b79549-eea7-45d2-ad18-aaa8f1ac67f5.png)

**Comment by muznabin12** [comment]
Got vnc working the first time around then the connection ended and I can't connect anymore.

**Comment by muznabin12** [comment]
Shows this after sometimes and vncviwer says port can't be contacted
![Screenshot_20220620-030133_Termux](https://user-images.githubusercontent.com/52606690/174500228-f6d69cb3-5029-41a9-b454-79489bb3f6c2.png)

**Comment by BDhackers009** [comment]
> Shows this after sometimes and vncviwer says port can't be contacted ![Screenshot_20220620-030133_Termux](https://user-images.githubusercontent.com/52606690/174500228-f6d69cb3-5029-41a9-b454-79489bb3f6c2.png)

Okay sir let me check

**Comment by NeilOscar34** [comment]
Please help me to solve this problem 🥺 🙏 🥺
When I type vnstart it shows:- hostname: Name or service not known
vncserver: Could not acquire fully qualified host name of this machine.
![Screenshot_20220827-095524_Termux](https://user-images.githubusercontent.com/98377736/187014436-e08a1bf7-13a5-49e6-bf42-f33b99403037.png)

Then i tried to install again bash gui.sh it shows:- sudo: unable to resolve host kali: Name or service not known
![problem](https://user-images.githubusercontent.com/98377736/187014536-7b82d4b0-d5b9-4108-bb1c-10ec99eb7563.png)

**Comment by BDhackers009** [comment]
> Please help me to solve this problem 🥺 🙏 🥺 When I type vnstart it shows:- hostname: Name or service not known vncserver: Could not acquire fully qualified host name of this machine. ![Screenshot_20220827-095524_Termux](https://user-images.githubusercontent.com/98377736/187014436-e08a1bf7-13a5-49e6-bf42-f33b99403037.png)
> 
> Then i tried to install again bash gui.sh it shows:- sudo: unable to resolve host kali: Name or service not known ![problem](https://user-images.githubusercontent.com/98377736/187014536-7b82d4b0-d5b9-4108-bb1c-10ec99eb7563.png)

Did you change your hostname to kali? if you do so.. please change it back to localhost

**Comment by bortan1** [comment]
> Wherever i type vncstart it shows nothing and i cant connect to vnc🥲

what I did was the following:
sudo apt-get purge tigervnc-common tigervnc-standalone-server tigervnc-tools
sudo apt autoremove -y
sudo apt install tightvncserver
vncserver
vncserver -kill :1
vncpasswd
cd .vnc/
mv xstartup xstartup.old
nano xstartup
add this to the file:
#!/bin/bash
xrdb $HOME/.Xresources
startxfce4 &
save and exit (ctrl+x then press y)
chmod +x xstartup
your are done. you can now start your vnc server using: vncserver
