### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by mizzunet** [modded-ubuntu/modded-ubuntu#7]
I installed it then given the username as "missu" then I re-opened termux and ran "ubuntu" that returned this 
```
~ $ ubuntu
su: user missu does not exist
```

**Comment by bdhackers69** [comment]
Reinstall ubuntu... because i think your user had not created successfully...if you wanted to fix it  then type the commands in termux:-
$proot-distro logjn ubuntu-20.04
and then run the user.sh script again....it will fix the problem

**Comment by mizzunet** [comment]
It was the ROM caused it
