### ISSUE TITLE
Blender is not working 

### ISSUE THREAD

**Issue by m1w263478** [modded-ubuntu/modded-ubuntu#71]
Blender and Openshot is not working please solve the problem

**Comment by BDhackers009** [comment]
https://youtu.be/c_HFvcS0Xdg

you can follow this video to install blender

**Comment by ArtOfWorking** [comment]
Now this video is not on youtube to install Blender
how can we install blender
not opening

**Comment by ArtOfWorking** [comment]
Now this video is not on youtube to install Blender
how can we install blender
not opening

**Comment by BDhackers009** [comment]
> Now this video is not on youtube to install Blender how can we install blender not opening

let me check if I can find any solution I will inform you sir.

**Comment by ArtOfWorking** [comment]
> > Now this video is not on youtube to install Blender how can we install blender not opening
> 
> let me check if I can find any solution I will inform you sir.
> 
> EDIT:- I checked and Blender is working fine.Install blender with ` sudo apt install blender` then you can launch blender from terminal by typing ` blender` or simply run it from application menu.
> 
> ![Screenshot_20230130-043910_VNC Viewer](https://user-images.githubusercontent.com/67186139/215360454-e80a4343-af0f-459f-93f2-c3dc1a3b7b74.png)

Color management: using fallback mode for management
Color management: Error could not find role data role.
Color management: scene view "Filmic" not found, setting default "Standard".
X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  131 (MIT-SHM)
  Minor opcode of failed request:  2 (X_ShmDetach)
  Segment id in failed request:  0x3000019
  Serial number of failed request:  183
  Current serial number in output stream:  184
