### ISSUE TITLE
Vnc not work

### ISSUE THREAD

**Issue by majdhdr** [modded-ubuntu/modded-ubuntu#72]
![20220731_191702.jpg](https://user-images.githubusercontent.com/74968081/182035670-03905933-b600-4fff-b057-14fad1d61f08.jpg)

**Comment by BDhackers009** [comment]
I think that error is because of you....you changed the hostname manually...first put the previous hostname and then try

**Comment by majdhdr** [comment]
> I think that error is because of you....you changed the hostname manually...first put the previous hostname and then try

It' work
Think you

**Comment by BDhackers009** [comment]
> > I think that error is because of you....you changed the hostname manually...first put the previous hostname and then try
> 
> It' work Think you

thanks for using our repository...dont forgot to give a star
