### ISSUE TITLE
Browser NOT WORKING!

### ISSUE THREAD

**Issue by StormTheXef** [modded-ubuntu/modded-ubuntu#73]
FireFox isn't working bc i can't open it from terminal bc it says i need to use snap but we cant use it in proot and if i open it using it's icon form applications it's not working! it gives and error btw when i open it from terminal it says this :
"Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox"

**Comment by StormTheXef** [comment]
@BDhackers009 Please Help🙂

**Comment by BDhackers009** [comment]
> @BDhackers009 Please Help🙂

install firefox with command:- sudo apt install firefox -y

**Comment by StormTheXef** [comment]
> > @BDhackers009 Please Help🙂
> 
> install firefox with command:- sudo apt install firefox -y

Brooo the same problem i reinstalled it like 5 times! Evern Chrome and Chromium🙁
![Screenshot_20220814-033314](https://user-images.githubusercontent.com/103287938/184518868-c54a33ef-4b80-49f6-8eb5-5735c488ceb2.png)

**Comment by StormTheXef** [comment]
@BDhackers009 Please Help Me🖤

**Comment by StormTheXef** [comment]
@BDhackers009 pleaaaase

**Comment by InikoMatthewPro** [comment]
> > > @BDhackers009 Please Help🙂
> > 
> > 
> > install firefox with command:- sudo apt install firefox -y
> 
> Brooo the same problem i reinstalled it like 5 times! Evern Chrome and Chromium🙁 ![Screenshot_20220814-033314](https://user-images.githubusercontent.com/103287938/184518868-c54a33ef-4b80-49f6-8eb5-5735c488ceb2.png)

Try this command
```
sudo snap install firefox
```

**Comment by InikoMatthewPro** [comment]
If you want chromium, will be not working

**Comment by BDhackers009** [comment]
> @BDhackers009 pleaaaase

Sir sorry for late reply. I have SSC exam after 5 days thats why I'm very inactive.Please wait I'm working on it. Today or tomorrow I will update you. thanks

**Comment by BDhackers009** [comment]
> @BDhackers009 pleaaaase

though its not a problem of our script its a problem of ubuntu 22.

I got the solution:- https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04/amp

please go to that site and follow it...

in the next update we will patch it.

**Comment by BDhackers009** [comment]
> > > @BDhackers009 pleaaaase
> > 
> > 
> > though its not a problem of our script its a problem of ubuntu 22.
> > I got the solution:- https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04/amp
> > please go to that site and follow it...
> > in the next update we will patch it.
> 
> It doesn't work. Here is what I get when I try to add the repository: sudo add-apt-repository ppa:mozillateam/ppa Traceback (most recent call last): File "/usr/bin/add-apt-repository", line 364, in sys.exit(0 if addaptrepo.main() else 1) File "/usr/bin/add-apt-repository", line 347, in main shortcut = handler(source, **shortcut_params) File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler return handler(shortcut, **kwargs) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in **init** if self.lpppa.publish_debug_symbols: File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa self._lpppa = self.lpteam.getPPAByName(name=self.ppaname) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam self._lpteam = self.lp.people(self.teamname) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp self._lp = login_func("%s.%s" % (self.**module**, self.**class**.**name**), File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously return cls( File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in **init** super(Launchpad, self).**init**( File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in **init** self._wadl = self._browser.get_wadl_application(self._root_uri) File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application response, content = self._request(url, media_type=wadl_type) File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request response, content = self._request_and_retry( File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry response, content = self._connection.request( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 1578, in request conn = self.connections[conn_key] = connection_type( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 1097, in **init** context = _build_ssl_context( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 147, in _build_ssl_context context = ssl.SSLContext(DEFAULT_TLS_VERSION) File "/usr/lib/python3.10/ssl.py", line 495, in **new** self = _SSLContext.**new**(cls, protocol) ssl.SSLError: [SSL] malloc failure (_ssl.c:3063)

Try to reinstall python3 and python-is-python3 then try...see if it works or not

**Comment by bortan1** [comment]
> 

after running
sudo apt reinstall python3 python-is-python3
I am getting the same issue

**Comment by BDhackers009** [comment]
> > 
> 
> after running sudo apt reinstall python3 python-is-python3 I am getting the same issue

sir the problem is fixed you can now install python3 python-is-python3 python3-pip.
if you have pip related issue kindly refer to this repository:- [click](https://github.com/bdhackers009/fixpip3)
