### ISSUE TITLE
Browser not working

### ISSUE THREAD

**Issue by bortan1** [modded-ubuntu/modded-ubuntu#76]
The browsers don't work. I tried the provided solution for mozilla and here is what I get:
 sudo add-apt-repository ppa:mozillateam/ppa                             Traceback (most recent call last):                                                                        File "/usr/bin/add-apt-repository", line 364, in <module>                                                 sys.exit(0 if addaptrepo.main() else 1)                                                               File "/usr/bin/add-apt-repository", line 347, in main                                                     shortcut = handler(source, **shortcut_params)                                                         File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler       return handler(shortcut, **kwargs)                                                                    File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__                     if self.lpppa.publish_debug_symbols:                                                                  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa                       self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)                                             File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam                      self._lpteam = self.lp.people(self.teamname)                                                          File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp                           self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),                           File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously           return cls(                                                                                           File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__                    super(Launchpad, self).__init__(                                                                      File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__               self._wadl = self._browser.get_wadl_application(self._root_uri)                                       File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application                                                                                                           response, content = self._request(url, media_type=wadl_type)                                          File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request               response, content = self._request_and_retry(                                                          File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry     response, content = self._connection.request(                                                         File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1578, in request                         conn = self.connections[conn_key] = connection_type(                                                  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1097, in __init__                        context = _build_ssl_context(                                                                         File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 147, in _build_ssl_context               context = ssl.SSLContext(DEFAULT_TLS_VERSION)                                                         File "/usr/lib/python3.10/ssl.py", line 495, in __new__                                                   self = _SSLContext.__new__(cls, protocol)                                                           ssl.SSLError: [SSL] malloc failure (_ssl.c:3063)

**Comment by BDhackers009** [comment]
> The browsers don't work. I tried the provided solution for mozilla and here is what I get: sudo add-apt-repository ppa:mozillateam/ppa Traceback (most recent call last): File "/usr/bin/add-apt-repository", line 364, in sys.exit(0 if addaptrepo.main() else 1) File "/usr/bin/add-apt-repository", line 347, in main shortcut = handler(source, **shortcut_params) File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler return handler(shortcut, **kwargs) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in **init** if self.lpppa.publish_debug_symbols: File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa self._lpppa = self.lpteam.getPPAByName(name=self.ppaname) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam self._lpteam = self.lp.people(self.teamname) File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp self._lp = login_func("%s.%s" % (self.**module**, self.**class**.**name**), File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously return cls( File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in **init** super(Launchpad, self).**init**( File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in **init** self._wadl = self._browser.get_wadl_application(self._root_uri) File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application response, content = self._request(url, media_type=wadl_type) File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request response, content = self._request_and_retry( File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry response, content = self._connection.request( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 1578, in request conn = self.connections[conn_key] = connection_type( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 1097, in **init** context = _build_ssl_context( File "/usr/lib/python3/dist-packages/httplib2/**init**.py", line 147, in _build_ssl_context context = ssl.SSLContext(DEFAULT_TLS_VERSION) File "/usr/lib/python3.10/ssl.py", line 495, in **new** self = _SSLContext.**new**(cls, protocol) ssl.SSLError: [SSL] malloc failure (_ssl.c:3063)

looks like It's ssl related error...i Don't get the error when i tried

**Comment by Reddysan1433** [comment]
Yah bro
Me to got same problem, but I found the solution for that problem
Here,
1.Remove old version/default version of fire fox
sudo snap remove firefox

2.Add Morzilla's repository
sudo add-apt-repository ppa:mozillateam/ppa

3.Set Mozilla as prefered source
echo ' Package: * Pin: release o=LP-PPA-mozillateam Pin-Priority: 1001 ' | sudo tee /etc/apt/preferences.d/mozilla-firefox

4.Now install new Morzilla version of Firefox
sudo apt-get install firefox-esr

With these steps you installed firefox but you still need to set this brower as default.

1.Right click on browser,Then click on properties.

![Screenshot_20220912-185223.jpg](https://user-images.githubusercontent.com/109979094/189666065-8d656846-b105-445b-a2d3-60b6530e5a0c.jpg)

2.Click on + symble, Search for firefox & add.
![Screenshot_20220912-185258.jpg](https://user-images.githubusercontent.com/109979094/189666469-8530350e-01ff-430b-aed0-bf50b2b36f63.jpg)

3.Click on other browser icon & remove them.
```

**Comment by issa331** [comment]
Je n'arrive pas à installer l'outil

**Comment by EuropaFantasy** [comment]
Moi non plus

**Comment by EuropaFantasy** [comment]
Sudo snap remove donne can't communicate with server

**Comment by BDhackers009** [comment]
> Sudo snap remove donne can't communicate with server

there is already a solution for that.

run ` curl https://raw.githubusercontent.com/modded-ubuntu/modded-ubuntu/v2.0/distro/firefox.sh | sudo bash` and it will install firefox for you. We will add this fix by default in the next update of modded ubuntu.

**Comment by EuropaFantasy** [comment]
ThanksEnvoyé à partir de Outlook pour Android

**Comment by EuropaFantasy** [comment]
It is workingEnvoyé à partir de Outlook pour Android

**Comment by BDhackers009** [comment]
> It is workingEnvoyé à partir de Outlook pour Android

you're most welcome sir. Please use English because I cannot understand fully what are you saying
