### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by Manusiamars123** [modded-ubuntu/modded-ubuntu#8]
/usr/local/bin/vncstart: line 2: vncserver: command not found
![Screenshot_2021-06-27-16-40-24-77_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/86552619/123539924-640ad680-d766-11eb-969f-bed66aeef866.png)

**Comment by BDhackers009** [comment]
try reinstall it or run vncserver manually by typing 

vncserver

**Comment by ShivaShirsath** [comment]
```
chmod +x *
bash gui.sh
```

**Comment by ShivaShirsath** [comment]
[Install VNC](https://github.com/ShivaShirsath/VNC)
