### ISSUE TITLE
Problem Of Connection

### ISSUE THREAD

**Issue by SundarVora** [modded-ubuntu/modded-ubuntu#81]
Whenever I start my Ubuntu through vncserver , after a couple of minutes it is showing me a message of connection lost even I have an excellent wifi speed.

Please solve this problem as soon as possible

**Comment by BDhackers009** [comment]
> 

connection lost of what? internet or vncserver?

**Comment by MininxD** [comment]
try run `vncserver -localhost no`
with this you can view VNC using your local IP from wifi or hotspot

**Comment by AleksandrKrasovski** [comment]
Hello. I have two problems with:
- VNC Viewer freezing
- storage device overflow.
My devices are:
- Huawei MatePad 11 with Harmony OS
- Poco F3 with Android 12 under MIUI Global 13.
------ VNC Viewer freezing ------
In Termux everything is ok (I think so):
Report issues at https://termux.dev/issues
~ $ ubuntu
AlIv@localhost:~$ vncstart
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Sfgj7bj4pZ,guid=211add0a25a243ce8d80a1046398da60
DBUS_SESSION_BUS_PID=12306

New Xtigervnc server 'localhost.localdomain:1 (AlIv)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/AlIv/.vnc/passwd :1 to connect to the VNC server.
-----
In VNC Viewer:
After one-two click on any fold/icon on the screen the Ubuntu OS is freezing finally. But I can move the cursor. 
------ storage device overflow ------
Poco F3 has additional problem. All free device memory about 200 GB is full by Termux files.
------ 
I am ready to provide additional information on your requirement. Please note that I am a new with Linux OS.

**Comment by AleksandrKrasovski** [comment]
[termux.md](https://github.com/modded-ubuntu/modded-ubuntu/files/10222243/termux.md)

**Comment by AleksandrKrasovski** [comment]
[termux.md](https://github.com/modded-ubuntu/modded-ubuntu/files/10222255/termux.md)

**Comment by BDhackers009** [comment]
this problem is fixed.
