### ISSUE TITLE
How can I access to VNC server from another device?

### ISSUE THREAD

**Issue by WSQS** [modded-ubuntu/modded-ubuntu#82]
What should I do to make VNC viewer of another device connect to the Ubuntu? Or, what port should I choose?

**Comment by WSQS** [comment]
I figure it out, By using tightvncserver instead, I can do this.

**Comment by MininxD** [comment]
> What should I do to make VNC viewer of another device connect to the Ubuntu? Or, what port should I choose?

try run vncserver with option "-localhost no"
`vncserver -localhost no`
