### ISSUE TITLE
how can i reset password if forgotten

### ISSUE THREAD

**Issue by BNLOS** [modded-ubuntu/modded-ubuntu#87]
hey i just installed the os but when i finished installing user the password i gave doesn't work

**Comment by BDhackers009** [comment]
this problem can be happened when the modded-ubuntu not installed correctly.

1. you can reinstall modded-ubuntu
2. Login to ubuntu as root user from termux using :- ` proot-distro login ubuntu  ` then add  a new user or change the existing users password. If you add a new user then you must change the  ` ubuntu ` script which is located in ` /data/data/com.termux/files/usr/bin/ubuntu ` open that script and change the existing username with the new username :)

**Comment by BNLOS** [comment]
thank u
