### ISSUE TITLE
Span error

### ISSUE THREAD

**Issue by ArtOfWorking** [modded-ubuntu/modded-ubuntu#88]
Command :-sudo snap install jupyter
Error:- 
error: cannot communicate with server: Post "http://localhost/v2/snaps/jupyter": dial unix /run/snapd.socket: connect: no such file or directory
![Screenshot_2023-01-27-16-37-03-564_com termux](https://user-images.githubusercontent.com/123292005/215071937-0967f0f2-0b56-4eea-b287-1031f2abbc59.jpg)

**Comment by BDhackers009** [comment]
snapd service cannot be run inside prooted environment.

**Comment by ArtOfWorking** [comment]
> snapd service cannot be run inside prooted environment.

Oh thanks
