### ISSUE TITLE
Failed to install Snap Store in ubuntu 22.04

### ISSUE THREAD

**Issue by SUMITDEY69** [modded-ubuntu/modded-ubuntu#89]
Hello Devs,

I'm using *Realme 6* mobile,
I'm unable to install *Snap store* in ubuntu 22.04.

It shows the following lines ->
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

error: cannot communicate with server: Post "http://localhost/v2/snaps/snap-store": dial unix /run/snapd.socket: connect: no such file or directory

How to solve this ?

**Comment by BDhackers009** [comment]
Proot cannot run systemd services which means snapd cannot be run inside modded-ubuntu or any kind of prooted distro.
