### ISSUE TITLE
Vnc black screen 

### ISSUE THREAD

**Issue by Frekkia97** [modded-ubuntu/modded-ubuntu#90]
Hi, have a problem, installation is all ok without error but vnc show a black screen and the cursor is a square. Can you help me? Many thanks

**Comment by BDhackers009** [comment]
> n you

you might have problem with installation of xfce4 .try installing xfce4 manually.

```
sudo apt install xfce4* -y
```

Then try to start vncserver again

**Comment by Frekkia97** [comment]
I try to install xfce4 but nothing, I installed and reinstalled the complete distro but nothing

**Comment by Frekkia97** [comment]
> > n you
> 
> you might have problem with installation of xfce4 .try installing xfce4 manually.
> 
> ```
> sudo apt install xfce4* -y
> ```
> 
> Then try to start vncserver again

I try to install xfce4 but nothing, I installed and reinstalled the complete distro but nothing

**Comment by BDhackers009** [comment]
show me a screenshot when you run the vncserver and also show me the output of 

` which xfce4-session`

` uname -m`

**Comment by Frekkia97** [comment]
> show me a screenshot when you run the vncserver and also show me the output of
> 
> ` which xfce4-session`
> 
> ` uname -m`

![Screenshot_20230130_232147_Termux](https://user-images.githubusercontent.com/123765934/215609435-7968b0ad-6c10-4e86-bbef-75c003be64f8.jpg)

**Comment by BDhackers009** [comment]
do you have dbus installed?

Try ` sudo apt install dbus-x11`

**Comment by Frekkia97** [comment]
> do you have dbus installed?
> 
> Try ` sudo apt install dbus-x11`

Yes installed :(

**Comment by BDhackers009** [comment]
> > do you have dbus installed?
> > Try ` sudo apt install dbus-x11`
> 
> Yes installed :(

I see :( . This never happened. Do one thing try to install any other distro manually. like ubuntu or debian.

` pkg upg -y;pkg i proot-distro -y;proot-distro install ubuntu`

` proot-distro login ubuntu` 

` apt update && yes | apt upgrade && yes | apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server at-spi2-core librsvg2-common tigervnc-tools tigervnc-common` 

Then run vncserver

` vncserver `

Then check if it's working or not. If it's working then we will go deep and try to fix your problem and if it's not working then you have problem with your device :).

**Comment by Frekkia97** [comment]
> > > do you have dbus installed?
> > > Try ` sudo apt install dbus-x11`
> > 
> > 
> > Yes installed :(
> 
> I see :( . This never happened. Do one thing try to install any other distro manually. like ubuntu or debian.
> 
> ` pkg upg -y;pkg i proot-distro -y;proot-distro install ubuntu`
> 
> ` proot-distro login ubuntu`
> 
> ` apt update && yes | apt upgrade && yes | apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server at-spi2-core librsvg2-common tigervnc-tools tigervnc-common`
> 
> Then run vncserver
> 
> `vncserver`
> 
> Then check if it's working or not. If it's working then we will go deep and try to fix your problem and if it's not working then you have problem with your device :).

Yes the other distro is ok, andronix and proot-distro

**Comment by BDhackers009** [comment]
> > > > do you have dbus installed?
> > > > Try ` sudo apt install dbus-x11`
> > > 
> > > 
> > > Yes installed :(
> > 
> > 
> > I see :( . This never happened. Do one thing try to install any other distro manually. like ubuntu or debian.
> > ` pkg upg -y;pkg i proot-distro -y;proot-distro install ubuntu`
> > ` proot-distro login ubuntu`
> > ` apt update && yes | apt upgrade && yes | apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server at-spi2-core librsvg2-common tigervnc-tools tigervnc-common`
> > Then run vncserver
> > `vncserver`
> > Then check if it's working or not. If it's working then we will go deep and try to fix your problem and if it's not working then you have problem with your device :).
> 
> Yes the other distro is ok, andronix and proot-distro

Try removing the modded-ubuntu and then install it again.It will be better if you "clear data" of Termux then again install it from beginning.Sorry sir I don't understand what's tha problem with your installation yet.

**Comment by twinklebob** [comment]
I've had this same problem. It still happens if I try a fresh ubuntu proot install. I have tried everything, including completely removing and reinstalling termux. I am completely lost.

The vnc server will connect, but I am left with a completely black screen if I use `modded-ubuntu` and a small window for clipboard management otherwise.

Either way, if I try and `startxfce4` I am presented with a bunch of errors:

```
New Xtigervnc server 'localhost.localdomain:1 (root)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /root/.vnc/passwd :1 to connect to the VNC server.

root@localhost:~# export DISPLAY=:1 && startxfce4
/usr/bin/startxfce4: X server already running on display :1
xfce4-session: No SSH authentication agent found

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.051: Failed to spawn gpg-agent: Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.063: Unable to launch "xfwm4": Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.065: Unable to launch "xfsettingsd": Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.068: Unable to launch "xfce4-panel": Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.070: Unable to launch "Thunar": Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.071: Unable to launch "xfdesktop": Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.084: Unable to launch "xfce4-screensaver" (specified by autostart/xfce4-screensaver.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.087: Unable to launch "xiccd" (specified by autostart/xiccd.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.089: Unable to launch "/usr/lib/aarch64-linux-gnu/xfce4/notifyd/xfce4-notifyd" (specified by autostart/xfce4-notifyd.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.098: Unable to launch "xfsettingsd" (specified by autostart/xfsettingsd.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.102: Unable to launch "start-pulseaudio-x11" (specified by autostart/pulseaudio.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.105: Unable to launch "xdg-user-dirs-update" (specified by autostart/xdg-user-dirs.desktop): Failed to close file descriptor for child process (Invalid argument)

(xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.114: Unable to launch "/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1" (specified by autostart/polkit-gnome-authentication-agent-1.desktop): Failed to close file descriptor for child process (Invalid argument)
```

Output of uname -m: `aarch64`

However, this does not happen if I use proot-distro to install debian and follow the other steps there.

**Comment by BDhackers009** [comment]
> I've had this same problem. It still happens if I try a fresh ubuntu proot install. I have tried everything, including completely removing and reinstalling termux. I am completely lost.
> 
> The vnc server will connect, but I am left with a completely black screen if I use `modded-ubuntu` and a small window for clipboard management otherwise.
> 
> Either way, if I try and `startxfce4` I am presented with a bunch of errors:
> 
> ```
> New Xtigervnc server 'localhost.localdomain:1 (root)' on port 5901 for display :1.
> Use xtigervncviewer -SecurityTypes VncAuth -passwd /root/.vnc/passwd :1 to connect to the VNC server.
> 
> root@localhost:~# export DISPLAY=:1 && startxfce4
> /usr/bin/startxfce4: X server already running on display :1
> xfce4-session: No SSH authentication agent found
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.051: Failed to spawn gpg-agent: Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.063: Unable to launch "xfwm4": Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.065: Unable to launch "xfsettingsd": Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.068: Unable to launch "xfce4-panel": Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.070: Unable to launch "Thunar": Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.071: Unable to launch "xfdesktop": Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.084: Unable to launch "xfce4-screensaver" (specified by autostart/xfce4-screensaver.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.087: Unable to launch "xiccd" (specified by autostart/xiccd.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.089: Unable to launch "/usr/lib/aarch64-linux-gnu/xfce4/notifyd/xfce4-notifyd" (specified by autostart/xfce4-notifyd.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.098: Unable to launch "xfsettingsd" (specified by autostart/xfsettingsd.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.102: Unable to launch "start-pulseaudio-x11" (specified by autostart/pulseaudio.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.105: Unable to launch "xdg-user-dirs-update" (specified by autostart/xdg-user-dirs.desktop): Failed to close file descriptor for child process (Invalid argument)
> 
> (xfce4-session:27043): xfce4-session-WARNING **: 17:30:28.114: Unable to launch "/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1" (specified by autostart/polkit-gnome-authentication-agent-1.desktop): Failed to close file descriptor for child process (Invalid argument)
> ```
> 
> Output of uname -m: `aarch64`
> 
> However, this does not happen if I use proot-distro to install debian and follow the other steps there.

Try running 

`vncserver -xstartup /usr/bin/xfce4-session `

and try to connect. I cannot give a solution if i cant reproduce the error itself .

**Comment by storytellerF** [comment]
There is no xstartup in .vnc folder

**Comment by storytellerF** [comment]
```
dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name modded-ubuntu -xstartup
```
>New Xtigervnc server 'modded-ubuntu' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/mi11/.vnc/passwd :1 to connect to the VNC server.
![Screenshot_2023-08-09-00-03-17-075_com gaurav avnc](https://github.com/modded-ubuntu/modded-ubuntu/assets/34095089/5fa3f3bb-dc50-4608-a0c9-d11f5b26a816)

**Comment by mio-19** [comment]
A similar issue: https://github.com/CypherpunkArmory/UserLAnd/issues/1784
