### ISSUE TITLE
Blander not opening

### ISSUE THREAD

**Issue by ArtOfWorking** [modded-ubuntu/modded-ubuntu#91]
How to install in modded Ubuntu?

**Comment by BDhackers009** [comment]
> How to install in modded Ubuntu?
Install it with:-
` sudo apt update && sudo apt upgrade -y && sudo apt install blender -y` 

Run it with:-

` blender`

**Comment by ArtOfWorking** [comment]
> > How to install in modded Ubuntu?
> 
> Install it with:- ` sudo apt update && sudo apt upgrade -y && sudo apt install blender -y`
> 
> Run it with:-
> 
> ` blender`

Error on blender command:- 

Color management: using fallback mode for management
Color management: Error could not find role data role.
Color management: scene view "Filmic" not found, setting default "Standard".
X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  131 (MIT-SHM)
  Minor opcode of failed request:  2 (X_ShmDetach)
  Segment id in failed request:  0x2000019
  Serial number of failed request:  183
  Current serial number in output stream:  184

**Comment by ArtOfWorking** [comment]
Err

> > How to install in modded Ubuntu?
> 
> Install it with:- ` sudo apt update && sudo apt upgrade -y && sudo apt install blender -y`
> 
> Run it with:-
> 
> ` blender`

Error on blender command:- 

Color management: using fallback mode for management
Color management: Error could not find role data role.
Color management: scene view "Filmic" not found, setting default "Standard".
X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  131 (MIT-SHM)
  Minor opcode of failed request:  2 (X_ShmDetach)
  Segment id in failed request:  0x2000019
  Serial number of failed request:  183
  Current serial number in output stream:  184

**Comment by BDhackers009** [comment]
> > > How to install in modded Ubuntu?
> > 
> > 
> > Install it with:- ` sudo apt update && sudo apt upgrade -y && sudo apt install blender -y`
> > Run it with:-
> > ` blender`
> 
> Error on blender command:-
> 
> Color management: using fallback mode for management Color management: Error could not find role data role. Color management: scene view "Filmic" not found, setting default "Standard". X Error of failed request: BadShmSeg (invalid shared segment parameter) Major opcode of failed request: 131 (MIT-SHM) Minor opcode of failed request: 2 (X_ShmDetach) Segment id in failed request: 0x2000019 Serial number of failed request: 183 Current serial number in output stream: 184

I don't think so blender can be fully functional on prooted distro s
