### ISSUE TITLE
Application Softwares

### ISSUE THREAD

**Issue by herocoder14** [modded-ubuntu/modded-ubuntu#92]
I want to know about each and every Application that can't be installed in this Proot Distro

**Comment by herocoder14** [comment]
`bash <(curl -fsSL "https://raw.githubusercontent.com/modded-ubuntu/config/main/firefox.sh") # Edit this line after merge`
`bash <(curl -fsSL "https://raw.githubusercontent.com/modded-ubuntu/modded-ubuntu/master/distro/firefox.sh")`
:For Firefox ?

**Comment by BDhackers009** [comment]
Yes the script is for installing firefox. Because in this version of Ubuntu you can't install firefox with apt. Ubuntu forces user to install firefox using snap but snap cannot be used in prooted environment that's why we created that script
