### ISSUE TITLE
xRDP support

### ISSUE THREAD

**Issue by Pixel702** [modded-ubuntu/modded-ubuntu#93]
There is currently no xRDP support or atleast I fail to achieve it as I tried using xRDP and the result was a plain black screen which is never visible on normal Ubuntu installation with xRDP.

**Comment by BDhackers009** [comment]
Sorry,we have customized our modded-ubuntu to work only with "vncserver" because you can't have a stable GUI experience with RDP but VNC.Hope you'll understand
