### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CreackDark** [modded-ubuntu/modded-ubuntu#99]
Hi, I've done all the steps, but I'm in trouble ![Screenshot_2023-03-17-12-48-45-283.jpeg](https://user-images.githubusercontent.com/122866762/225863738-3a549d22-1188-40fd-a2ca-bbb9697832ca.jpeg)

If the table vncstart gives an error please help me

**Comment by BDhackers009** [comment]
bruh! you're using legacy Termux. 

1. Download termux from [Click Here](https://github.com/termux/termux-app/releases)
2. Then follow the instructions.
3. run gui.sh as root means you have to run gui.sh with the following command ` sudo bash gui.sh `

**Comment by CreackDark** [comment]
Thank you 
![Screenshot_2023-03-17-20-39-27-181.jpeg](https://user-images.githubusercontent.com/122866762/226092844-73fb0355-6aaf-4ea0-903d-8278ccf4b86b.jpeg)
Sorry what to do

**Comment by CreackDark** [comment]
Thank you 
![Screenshot_2023-03-18-11-19-56-641.jpeg](https://user-images.githubusercontent.com/122866762/226093698-9fe2f7db-4aa2-4d98-9dae-1afbdae6197a.jpeg)
Sorry I knocked Ctrl + z
No problem ?

**Comment by CreackDark** [comment]
![Screenshot_2023-03-18-14-12-25-477.jpeg](https://user-images.githubusercontent.com/122866762/226100716-4aaf59c6-2bae-4cf6-8491-58f7eca27f68.jpeg)

Error For dpkg 🤔
Help

**Comment by BDhackers009** [comment]
> ![Screenshot_2023-03-18-14-12-25-477.jpeg](https://user-images.githubusercontent.com/122866762/226100716-4aaf59c6-2bae-4cf6-8491-58f7eca27f68.jpeg)
> 
> Error For dpkg 🤔 Help

In the first screenshot that wasn't any error that was an warning. and the 2nd screenshot tell us that you ran a apt command without sudo please run any apt command with sudo privileges like ` sudo apt install pkg_name`

**Comment by CreackDark** [comment]
Ohhh 
Ok thank You

**Comment by BDhackers009** [comment]
welcome
